name: PR Checks
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with coverage
        run: |
          source venv/bin/activate
          pytest --cov=utils --cov-report=term-missing
